#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S2, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          RollingGoalGripperRight, tmotorNXT, PIDControl)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          RollingGoalGripperLeft, tmotorNXT, PIDControl)
#pragma config(Motor,  mtr_Matrix_S1_1, RightFrontDrive, tmotorMatrix, PIDControl, driveRight, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, RightRearDrive, tmotorMatrix, PIDControl, driveRight, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, LeftFrontDrive, tmotorMatrix, PIDControl, driveLeft, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, LeftRearDrive, tmotorMatrix, PIDControl, driveLeft, encoder)
#pragma config(Motor,  mtr_Matrix_S2_1, LiftMotorRight, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S2_2, ConveyorDrive, tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S2_3, LiftMotorLeft, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S2_4, GathererMotor, tmotorMatrix, openLoop, encoder)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_1, RollingGoalGripperRight, tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_2, servo6,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_3, RollingGoalGripperLeft, tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_4, servo8,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"

/* NR says
It appears that there does exist a way to tell the nxt motors to hold a position.
(nMotorEncoderTarget[])
*/

int scaledJoyDrive(int i_joyY)
{
	// add Y offset to the joystick input and scale to 100; handle both positive and negative
	const float Yoffset = 13;
	// create a dead zone
	const int joyDead = 7;

	float joyY;
	int scaledY;
	joyY = (float)i_joyY;
	// part after "?" is positive joyY; part after ":" handles negative joyY
	if (abs(joyY)<joyDead)
	{
		scaledY = 0;
	}
	else
	{
		scaledY = (joyY>0) ? (int)(  (joyY + Yoffset) / (127 + Yoffset) * 100  ) : (int)((joyY - Yoffset) / (-128 - Yoffset) * -100);
	}

	return scaledY;
}

task main()
{

	int LeftDriveValue;
	int RightDriveValue;
	int ConveyorDriveValue;
	int GathererDriveValue;
	int LiftMotorLeftValue;
	int LiftMotorRightValue;

	bool driveReversed = false;

	bool wasReversePress = false;
	bool wasSweepUpPress = false;
	bool wasSweepDownPress = false;

	int gripTarget = 0;
	int sweepSpeed = 50;

	nMotorEncoder[RollingGoalGripperRight] = 0;
	nMotorEncoder[RollingGoalGripperLeft] = 0;
	bFloatDuringInactiveMotorPWM = false;

	waitForStart();

	while(true) // infinite loop:
	{
		getJoystickSettings(joystick); // update buttons and joysticks

		LeftDriveValue = scaledJoyDrive(joystick.joy1_y1);
		RightDriveValue = scaledJoyDrive(joystick.joy1_y2);
		ConveyorDriveValue = scaledJoyDrive(joystick.joy2_y1);
		GathererDriveValue = scaledJoyDrive(joystick.joy2_y2);

		switch (joystick.joy1_TopHat)
		{
		case 0:
			LeftDriveValue =  100;
			RightDriveValue = 100;
			break;
		case 1:
			LeftDriveValue = 50;
			RightDriveValue = 0;
		case 7:
			LeftDriveValue = 0;
			RightDriveValue = 50;
		case 4:
			LeftDriveValue =  -100;
			RightDriveValue = -100;
			break;
		case 3:
			LeftDriveValue = -50;
			RightDriveValue = 0;
		case 5:
			LeftDriveValue = 0;
			RightDriveValue = -50;
		case 6:
			LeftDriveValue = -50;
			RightDriveValue = 50;
			break;
		case 2:
			LeftDriveValue =  50;
			RightDriveValue = -50;
			break;
		}

		if(joy1Btn(6) == 0)
		{

			LeftDriveValue = LeftDriveValue / 2;
			RightDriveValue = RightDriveValue / 2;
		}

		if(joy1Btn(5) == 1)
		{
			if(!wasReversePress)
			{
				if (driveReversed)
					driveReversed = false;
				else
					driveReversed = true;
			}
			wasReversePress = true;
		}
		else
		{
			wasReversePress = false;
		}

		if(driveReversed == true)
		{
			int R = RightDriveValue;
			int L = LeftDriveValue;

			LeftDriveValue = R * -1;
			RightDriveValue = L * -1;
		}

		motor[LeftRearDrive] = LeftDriveValue;
		motor[RightRearDrive] = RightDriveValue;
		motor[LeftFrontDrive] = LeftDriveValue;
		motor[RightFrontDrive] = RightDriveValue;

		//---BEGIN SECOND CONTROLLER---//

		//Update grip motors
		if(joy2Btn(2) == 1)
		{
			gripTarget = 230;
		}
		if(joy2Btn(4) == 1)
		{
			gripTarget = 0;
		}

		//Maintain grip motors
		if(nMotorEncoder[RollingGoalGripperRight] > gripTarget+1)
		{
			motor[RollingGoalGripperRight] = -25;
		}
		else if(nMotorEncoder[RollingGoalGripperRight] < gripTarget-1)
		{
			motor[RollingGoalGripperRight] = 25;
		}
		else
		{
			motor[RollingGoalGripperRight] = 0;
		}
		if(nMotorEncoder[RollingGoalGripperLeft] > gripTarget+8) //adjusted for asymmetry
		{
			motor[RollingGoalGripperLeft] = -25;
		}
		else if(nMotorEncoder[RollingGoalGripperLeft] < gripTarget+6)
		{
			motor[RollingGoalGripperLeft] = 25;
		}
		else
		{
			motor[RollingGoalGripperLeft] = 0;
		}

		//update sweep on/off
		if(joy2Btn(1) == 1)
		{
			motor[GathererMotor]	= -sweepSpeed;
		}
		/*else
		{
			motor[GathererMotor]	= 0;
		}*/

		//update sweep speed
		switch(joystick.joy2_TopHat)
		{
				case 0:
					if (!wasSweepUpPress)
						sweepSpeed+=5;
					wasSweepUpPress = true;
					wasSweepDownPress = false;
					break;
				case 4:
					if (!wasSweepDownPress)
						sweepSpeed-=5;
					wasSweepDownPress = true;
					wasSweepUpPress = false;
					break;
				default:
					wasSweepDownPress = false;
					wasSweepUpPress = false;
		}

		//update lift
		if(joy2Btn(5) == 1)	{LiftMotorLeftValue = 99;}
		if(joy2Btn(6) == 1) {LiftMotorRightValue = 99;}
		if(joy2Btn(7) == 1)	{LiftMotorLeftValue = -99;}
		if(joy2Btn(8) == 1) {LiftMotorRightValue = -99;}

		motor[GathererMotor] = GathererDriveValue;
		motor[ConveyorDrive] = ConveyorDriveValue;
		motor[LiftMotorRight] = LiftMotorRightValue;
		motor[LiftMotorLeft] = LiftMotorLeftValue;
	}
}
