#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S2, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_1, RightFrontDrive, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, LeftFrontDrive, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, RightRearDrive, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, LeftRearDrive, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S2_1, ArmUpDown,     tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S2_2, motorI,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S2_3, motorJ,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S2_4, motorK,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_1, servo5,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_2, servo6,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_3, servo7,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_4, servo8,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"

int scaledJoyDrive(int i_joyY)
{
	// add Y offset to the joystick input and scale to 100; handle both positive and negative
	const float Yoffset = 13;
	// create a dead zone
	const int joyDead = 5;

	float joyY;
	int scaledY;

	joyY = (float)i_joyY;
	// part after "?" is positive joyY; part after ":" handles negative joyY
	if (abs(joyY)<joyDead)
  {
    scaledY = 0;
  }
  else
  {
    	scaledY = (joyY>0) ? (int)((joyY + Yoffset) / (127 + Yoffset) * 100) : (int)((joyY - Yoffset) / (-128 - Yoffset) * -100);
  }

	return scaledY;
}

task main()
{

	while(true)                        // infinite loop:
	{
 	 	getJoystickSettings(joystick);     // update buttons and joysticks
  	//moves tower motor
 	 	//motor[motorH] = scaledJoyDrive(joystick.joy1_y1);  // motorB's powerlevel is set to the left stick's current y-value

 	 	// test motor
 	 	//motor[motorH] = scaledJoyDrive(joystick.joy1_y1) / 3;  // motorB's powerlevel is set to the left stick's current y-value
		motor[LeftRearDrive] =  -1 * scaledJoyDrive(joystick.joy1_y1);  // motorB's powerlevel is set to the left stick's current y-value
  	motor[RightRearDrive] = scaledJoyDrive(joystick.joy1_y2);
  	motor[LeftFrontDrive] =  -1 * scaledJoyDrive(joystick.joy1_y1);
  	motor[RightFrontDrive] = scaledJoyDrive(joystick.joy1_y2);
	 }
}
