#pragma config(Sensor, S3,     IRSeeker,       sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c";

task main()
{
while(true)
	{
		clearDebugStream();
		writeDebugStream("The IR Seeker sensor's output is: %i", SensorValue[IRSeeker]);
		wait1Msec(100);
	}
}
