#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     DriveController, sensorI2CMuxController)
#pragma config(Sensor, S2,     MiscController, sensorNone)
#pragma config(Sensor, S3,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_Matrix_S1_1, RightFrontDrive, tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, RightRearDrive, tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, LeftFrontDrive, tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, LeftRearDrive, tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


// Drive control methods ___________________________________________________________________________

void goForward4x4(const int msTime, const int power)
{
	motor[RightFrontDrive] = power;
	motor[LeftFrontDrive] = power * -1;
	motor[RightRearDrive] = power;
	motor[LeftRearDrive] = power * -1;
	wait1Msec(msTime);
}

void goForwardFront(const int msTime, const int power) // goForwardFront = 	Forward front wheel drive
{
	motor[RightFrontDrive] = power;
	motor[LeftFrontDrive] = power * -1;
}

void goForwardRear(const int msTime, const int power) // goForwardRear = 		Forward rear wheel drive
{
	motor[RightRearDrive] = power;
	motor[LeftRearDrive] = power * -1;
}

void goBackward4x4(const int msTime, const int power)  // goBackward4x4 = 	Backward four wheel drive
{
	motor[RightFrontDrive] = power * -1;
	motor[LeftFrontDrive] = power;
	motor[RightRearDrive] = power * -1;
	motor[LeftRearDrive] = power;
	wait1Msec(msTime);
}

void turnLeft4x4(const int msTime, const int power) // turnLeft4x4 =				Turn left four wheel drive
{
	motor[RightFrontDrive] = power;
	motor[LeftFrontDrive] = power;
	motor[RightRearDrive] = power;
	motor[LeftRearDrive] = power;
	wait1Msec(msTime);
}

void turnLeftRear(const int msTime, const int power)  // turnLeft =					Turn left rear wheel drive
{
	motor[RightRearDrive] = power;
	motor[LeftRearDrive] = power;
	wait1Msec(msTime);
}

//__________________________________________________________________________________________


task main()
{

      nxtDisplayBigTextLine(4, "I'll never see this");
      wait1Msec(1000);


}
