#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     DriveController, sensorI2CMuxController)
#pragma config(Sensor, S2,     MiscController, sensorNone)
#pragma config(Sensor, S3,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_Matrix_S1_1, RightFrontDrive, tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, RightRearDrive, tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, LeftFrontDrive, tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, LeftRearDrive, tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void goForward4x4(const int msTime, const int power)
{
	motor[RightFrontDrive] = power;
	motor[LeftFrontDrive] = power * -1;
	motor[RightRearDrive] = power;
	motor[LeftRearDrive] = power * -1;
	wait1Msec(msTime);
}

task main()
{

goForward4x4(1000, 25);


}
