#pragma config(Motor,  motorA,          Motor,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[motorA] = -100;
	}

}
