#pragma config(Motor,  motorA,          ScoopLeft,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          ScoopRight,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"

int scaledJoyDrive(int i_joyY)
{
	// add Y offset to the joystick input and scale to 100; handle both positive and negative
	const float Yoffset = 13;
	const float Yoffset = 13;
	float joyY;
	int scaledY;
	joyY = (float)i_joyY;
	// part after "?" is positive joyY; part after ":" handles negative joyY
	if (abs(joyY)<2)
  {
    scaledY = 0;
  }
  else
  {
    	scaledY = (joyY>0) ? (int)((joyY + Yoffset) / (127 + Yoffset) * 100) : (int)((joyY - Yoffset) / (-128 - Yoffset) * -100);
  }

	return scaledY;
}

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);     // update buttons and joysticks
		motor[ScoopLeft] = scaledJoyDrive(joystick.joy1_y1) / -2;
		motor[ScoopRight] = scaledJoyDrive(joystick.joy1_y1) / -2;

		if(joystick.joy1_TopHat == 0)      // if the topmost button on joy1's D-Pad ('TopHat') is pressed:
  {
    motor[ScoopLeft] = - 25;
    motor[ScoopRight] = - 25;					// motors are run at a power level of 25
    wait1Msec(60);
  }
  	if(joystick.joy1_TopHat == 4)
  	{
  		motor[ScoopLeft] = 25;
    motor[ScoopRight] = 25;					// motors are run at a power level of 25
    wait1Msec(60);
  	}

	}
}
