#pragma config(Sensor, S1,     LightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x;
	while(true)
	{
		clearDebugStream();
		x = SensorValue[LightSensor];
		writeDebugStreamLine("Sensor value is %i", x);
		wait1Msec(200);
	}
}
