#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     DriveController, sensorNone)
#pragma config(Motor,  mtr_Matrix_S1_1, LeftFrontDrive, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, motorE,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorF,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


// Drive control methods ___________________________________________________________________________


// LeftFrontDrive
void LeftFrontTest(const int msTime, const int power)  // testing
{
	motor[LeftFrontDrive] = power;
	wait1Msec(msTime);
}

//__________________________________________________________________________________________


task main()
{

      LeftFrontTest(2000, 50);
      wait1Msec(1000);


}
