#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S2, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S3,     GyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          RollingGoalGripperRight, tmotorNXT, PIDControl)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          RollingGoalGripperLeft, tmotorNXT, PIDControl)
#pragma config(Motor,  mtr_Matrix_S1_1, LeftFrontDrive, tmotorMatrix, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, GathererMotor, tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, LeftRearDrive, tmotorMatrix, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, LiftMotorLeft, tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S2_1, RightFrontDrive, tmotorMatrix, PIDControl, driveRight, encoder)
#pragma config(Motor,  mtr_Matrix_S2_2, ConveyorDrive, tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S2_3, LiftMotorRight, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S2_4, RightRearDrive, tmotorMatrix, PIDControl, driveRight, encoder)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_1, servo5,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_2, servo6,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_3, servo7,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_4, servo8,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveMotors(float rf, float rr, float lf, float lr)
{
	float multiplyer = 1;

	motor[RightFrontDrive] = (rf * multiplyer)+1;
	motor[RightRearDrive] = (rr * multiplyer)+1;
	motor[LeftFrontDrive] = (lf * multiplyer);
	motor[LeftRearDrive] = (lr * multiplyer);
}

task main()
{
	int counter = 0;
	int summedValue = 0;
	int averagedValue = 0;
	int totalValue = 0;

	while(true)
	{
		counter = 0;
		summedValue = 0;
		averagedValue = 0;

		for(int counter = 0; counter < 100; counter++)
		{
			summedValue = summedValue + (SensorValue[GyroSensor] - 589);
			wait1Msec(1);
		}

		averagedValue = summedValue / 1000;
		totalValue = totalValue + averagedValue;

		if(totalValue < 175) {driveMotors(-20, -20, 20, 20);}

		if(totalValue > 185) {driveMotors(20, 20, -20, -20);}

		if(totalValue >= 175 && totalValue <= 185){driveMotors(0, 0, 0, 0);}

		displayCenteredBigTextLine(3, "%i", totalValue);
	}
}
