#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S2, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S4,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          RollingGoalGripperRight, tmotorNXT, PIDControl)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          RollingGoalGripperLeft, tmotorNXT, PIDControl)
#pragma config(Motor,  mtr_Matrix_S1_1, LeftFrontDrive, tmotorMatrix, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, GathererMotor, tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, LeftRearDrive, tmotorMatrix, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, LiftMotorLeft, tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S2_1, RightFrontDrive, tmotorMatrix, PIDControl, driveRight, encoder)
#pragma config(Motor,  mtr_Matrix_S2_2, ConveyorDrive, tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S2_3, LiftMotorRight, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S2_4, RightRearDrive, tmotorMatrix, PIDControl, driveRight, encoder)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_1, servo5,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_2, servo6,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_3, servo7,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_4, servo8,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

function driveMotors(int rf, int rr, int lf, int lr)
{
	motor[RightFrontDrive] = rf;
  motor[RightRearDrive] = rr;
  motor[LeftFrontDrive] = lf;
  motor[LeftRearDrive] = lr;
}

task main()
{
	while(true)
	{

		switch (SensorValue[IRSeeker])
 	 	{
  		case 5:
   	 		driveMotors(50,50,50,50);
    	break;

  		case 4:
   	 		driveMotors(55,55,35,35);
    	break;

  		case 6:
   	 		driveMotors(35,35,55,55);
    	break;

			case 1:
			case 2:
			case 3:
   	 		driveMotors(60,60,20,20);
    	break;

    	case 7:
    	case 8:
    	case 9:
   	 		driveMotors(20,20,60,60);
    	break;

  		default:
    	driveMotors(0,0,0,0);
  	}

	}
}
