#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S2, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_1, RightFrontDrive, tmotorMatrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, RightRearDrive, tmotorMatrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, LeftFrontDrive, tmotorMatrix, openLoop, driveLeft, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, LeftRearDrive, tmotorMatrix, openLoop, driveLeft, encoder)
#pragma config(Motor,  mtr_Matrix_S2_1, LiftMotorRight, tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_2, motorI,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S2_3, LiftMotorLeft, tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_4, motorK,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_1, RollingGoalGripperRight, tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_2, servo6,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S2_3, RollingGoalGripperLeft, tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_4, servo8,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Since the two servos are in opposite orientations, a greater servo value indicates a
higher position for the RollingGoalGripperRight servo, and a
lower  position for the RollingGoalGripperLeft servo.
Right is up at 255, down at 39
Left is up at 0, down at 237
*/
const int RGGRightUp = 255;
const int RGGLeftUp = 0;
const int RGGRightDown = 18;
const int RGGLeftDown = 238;

task main()
{
	//int RGGRi = 100;
	//int RGGLi = 100;
	//RGGRi = ServoValue[RollingGoalGripperRight];
	//RGGLi = ServoValue[RollingGoalGripperLeft];
	servoChangeRate[RollingGoalGripperLeft] = 4;
	servoChangeRate[RollingGoalGripperRight] = 4;
	servo[RollingGoalGripperRight] = RGGRightUp;
	servo[RollingGoalGripperLeft] = RGGLeftUp;
	wait1Msec(1000);
}
