#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_1, RightFrontDrive, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, RightRearDrive, tmotorMatrix, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, LeftFrontDrive, tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, LeftRearDrive, tmotorMatrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot() // sets all the wheel encoder values to 0, just to be sure they aren't something different.
{
	nMotorEncoder[RightFrontDrive] = 0;
  nMotorEncoder[RightRearDrive] = 0;
  nMotorEncoder[LeftFrontDrive] = 0;
  nMotorEncoder[LeftRearDrive] = 0;

  return;
} // end of the "initializeRobot" function


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


const float feetToTravel = 5.3;  // tells how many feet we want the robot to move

const float inchesToTravel = feetToTravel * 12; // takes number of feet and turns it into how many inches

const float wheelDiameter = 3.75;  // tells the diameter of our Matrix wheels in inches

const float ticksPerRevolution = 757.12;  // tells how many motor encoder ticks there are in a revolution

const float ticksToTravel = inchesToTravel * ticksPerRevolution / (wheelDiameter * 3.14159); // final number of
	// encoder ticks to travel, based off the specified number of feet



void accelerateGradually() // Accelerates gradually from 0 to 95% power in 0.525 seconds, to keep wheels from
// slipping and throwing off the encoder values
{
	motor[RightFrontDrive] = 2; // sets all the motor power values to 2% power
  motor[RightRearDrive] = 2;
  motor[LeftFrontDrive] = 2;
  motor[LeftRearDrive] = 2;

  wait1Msec(25); // waits 25 milliseconds (0.025 seconds)

  motor[RightFrontDrive] = 5; // sets all the motor power values to 5% power
  motor[RightRearDrive] = 5;
  motor[LeftFrontDrive] = 5;
  motor[LeftRearDrive] = 5;

  wait1Msec(25); // waits 25 milliseconds

  motor[RightFrontDrive] = 9;
  motor[RightRearDrive] = 9;
  motor[LeftFrontDrive] = 9;
  motor[LeftRearDrive] = 9;

  wait1Msec(25);

  motor[RightFrontDrive] = 12;
  motor[RightRearDrive] = 12;
  motor[LeftFrontDrive] = 12;
  motor[LeftRearDrive] = 12;

  wait1Msec(25);

  motor[RightFrontDrive] = 16;
  motor[RightRearDrive] = 16;
  motor[LeftFrontDrive] = 16;
  motor[LeftRearDrive] = 16;

  wait1Msec(25);

  motor[RightFrontDrive] = 20;
  motor[RightRearDrive] = 20;
  motor[LeftFrontDrive] = 20;
  motor[LeftRearDrive] = 20;

  wait1Msec(25);

  motor[RightFrontDrive] = 25;
  motor[RightRearDrive] = 25;
  motor[LeftFrontDrive] = 25;
  motor[LeftRearDrive] = 25;

  wait1Msec(25);

  motor[RightFrontDrive] = 30;
  motor[RightRearDrive] = 30;
  motor[LeftFrontDrive] = 30;
  motor[LeftRearDrive] = 30;

  wait1Msec(25);

  motor[RightFrontDrive] = 35;
  motor[RightRearDrive] = 35;
  motor[LeftFrontDrive] = 35;
  motor[LeftRearDrive] = 35;

  wait1Msec(25);

  motor[RightFrontDrive] = 40;
  motor[RightRearDrive] = 40;
  motor[LeftFrontDrive] = 40;
  motor[LeftRearDrive] = 40;

  wait1Msec(25);

  motor[RightFrontDrive] = 45;
  motor[RightRearDrive] = 45;
  motor[LeftFrontDrive] = 45;
  motor[LeftRearDrive] = 45;

  wait1Msec(25);

  motor[RightFrontDrive] = 50;
  motor[RightRearDrive] = 50;
  motor[LeftFrontDrive] = 50;
  motor[LeftRearDrive] = 50;

  wait1Msec(25);

  motor[RightFrontDrive] = 55;
  motor[RightRearDrive] = 55;
  motor[LeftFrontDrive] = 55;
  motor[LeftRearDrive] = 55;

  wait1Msec(25);

  motor[RightFrontDrive] = 60;
  motor[RightRearDrive] = 60;
  motor[LeftFrontDrive] = 60;
  motor[LeftRearDrive] = 60;

  wait1Msec(25);

  motor[RightFrontDrive] = 65;
  motor[RightRearDrive] = 65;
  motor[LeftFrontDrive] = 65;
  motor[LeftRearDrive] = 65;

  wait1Msec(25);

  motor[RightFrontDrive] = 70;
  motor[RightRearDrive] = 70;
  motor[LeftFrontDrive] = 70;
  motor[LeftRearDrive] = 70;

  wait1Msec(25);

  motor[RightFrontDrive] = 75;
  motor[RightRearDrive] = 75;
  motor[LeftFrontDrive] = 75;
  motor[LeftRearDrive] = 75;

  wait1Msec(25);

  motor[RightFrontDrive] = 80;
  motor[RightRearDrive] = 80;
  motor[LeftFrontDrive] = 80;
  motor[LeftRearDrive] = 80;

  wait1Msec(25);

  motor[RightFrontDrive] = 85;
  motor[RightRearDrive] = 85;
  motor[LeftFrontDrive] = 85;
  motor[LeftRearDrive] = 85;

  wait1Msec(25);

  motor[RightFrontDrive] = 90;
  motor[RightRearDrive] = 90;
  motor[LeftFrontDrive] = 90;
  motor[LeftRearDrive] = 90;

  wait1Msec(25);

  motor[RightFrontDrive] = 95; // sets all the motor power values to 95%
  motor[RightRearDrive] = 95;
  motor[LeftFrontDrive] = 95;
  motor[LeftRearDrive] = 95;

  wait1Msec(25); // waits 25 milliseconds
} // end of the "accelerateGradually" function


task main() // main task
{

  initializeRobot(); // calls the "initializeRobot" function

  //waitForStart(); // Wait for the beginning of autonomous phase.

  accelerateGradually(); // calls the "accelerateGradually" function

  while (nMotorEncoder[LeftFrontDrive] < ticksToTravel) // repeat this section of code (do not continue sequential
	// execution) until one of the motor encoder values (in this case, the left front motor) is greater than the
	// target number of ticks to move, calculated from the specified number of feet to move.
  {
  	motor[RightFrontDrive] = 100;  // sets all the motors to full power forward
  	motor[RightRearDrive] = 100;
  	motor[LeftFrontDrive] = 100;
  	motor[LeftRearDrive] = 100;
  }

  motor[RightFrontDrive] = -50; // sets all the motors to 50% power backwards, to brake the motors and the robot from
  motor[RightRearDrive] = -50;  // gliding further forward
  motor[LeftFrontDrive] = -50;
  motor[LeftRearDrive] = -50;

  wait10Msec(7); // waits 70 milliseconds (0.070 seconds)

  motor[RightFrontDrive] = 0; // sets all the motors to 0% power (off)
  motor[RightRearDrive] = 0;
  motor[LeftFrontDrive] = 0;
  motor[LeftRearDrive] = 0;
} // end of main function, end of program
